version: '3.1'

services:

  node:
    image: node:10-jessie
    restart: always
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../catalog:/root/app
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: thisispassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: thisispassword